### ISSUE TITLE
可以看一下pbr-m1的openwrt 应该可以直接刷就能用

### ISSUE THREAD

**Issue by jessons** [maikelwever/openwrt-15.05-wndr3700v5#1]
就是没有2.4g无线驱动，看dts不用分那么多区吧？我是r6220改了spi flash 刷了pbr m1的固件 基本能用，就是gpio口不对应，但是不影响使用。这个路由和6220板子完全一样

**Comment by maikelwever** [comment]
I dont speak Chinese, however, translating the message I'm assuming you want me to take a look at this: https://github.com/updateing/openwrt-r6220

2,4ghz we will see what to to about that in the future when the device actually boots openwrt and I can ssh into it. Maybe code from netgear site will help with that. If 5ghz works I'll be happy enough.

If you made patches yourself and device boots with those patches, feel free to submit a pull request.
